### ISSUE TITLE
A suggestion for in-scope parameters

### ISSUE THREAD

**Issue by lastguest** [mario-deluna/Tattoo#1]
Instead of the `this.data` form :

``` css
[a .ajax-trigger, href="/notes/save/"]
{
    this.data: { noteId: 123, userId: 42, revision: 1 }

    print "Save your Note"
}
```

You could write something like that :

``` css
[a .ajax-trigger, href="/notes/save/"]
{
   @noteId = 123
   @userId = 42
   @revision = 1 

   print "Save your Note"
}
```

more consistent with the already defined variable syntax.

What do you think?

**Comment by mario-deluna** [comment]
It's true `this` should be consistent with other variables. But I would not make any defined var inside a scope automatically a data attribute.

Lets say you got a user object `@user` inside that view. You don't want that the `.profile-container` implements the data attribute `@user` just because it's in his scope.

```
[div #profile-container]
{
    [a .btn.follow-ajax-trigger, href: "user/follow/ ]
    {
        @this.data.userId = @user.id
    }
}
```

Also I want to allow parent modifications so I think giving the `@this` var is the best way of creating an accessible tree: 

```
[ul .navigation]
{
    each @page in @pages
    {
        [li][a .navigation-item]
        {
            if @page.isActive()
            {
                @this.parent.class += 'active'
            }
        }
    }
}
```

Thanks for your input  :)

**Comment by lastguest** [comment]
> But I would not make any defined var inside a scope automatically a data attribute.

Right.

> Also I want to allow parent modifications so I think giving the `@this` var is the best way of creating an accessible tree

That's very cool.

BTW, nice job here, I like it :) :+1:
